apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "shared-infra.labels" . | nindent 4 }}
data:
  vault.hcl: |
    {{- if eq .Values.global.environment "development" }}
    ui = true
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
    }
    storage "raft" {
      path = "/vault/data"
    }
    {{- else }}
    ui = true
    listener "tcp" {
      tls_disable = 0
      address = "[::]:8200"
    }
    storage "raft" {
      path = "/vault/data"
      node_id = "vault-${POD_NAME}"
    }
    seal "awskms" {
      region     = "{{ .Values.vault.seal.region }}"
      kms_key_id = "{{ .Values.vault.seal.keyId }}"
    }
    {{- end }}
