apiVersion: v2
name: shared-infra
description: Shared Infrastructure for Scholar Spark Development Environment
type: application
version: 0.4.0
appVersion: "1.1.0"

dependencies:
  - name: gateway-api
    version: "0.8.0"
    repository: "https://kubernetes-sigs.github.io/gateway-api/charts"
    condition: gateway-api.enabled
