# Global settings
global:
  environment: development
  namespace: scholar-spark-dev

cilium:
  enabled: true
  hubble:
    enabled: true  # For observability
  loadBalancer:
    enabled: true
  ingressController:
    enabled: true
    defaultSecretName: scholar-spark-tls
    service:
      type: LoadBalancer

# Grafana configuration
grafana:
  enabled: true
  adminPassword: admin # Should be overridden in production
  persistence:
    enabled: true
    size: 1Gi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Tempo
          type: tempo
          url: http://tempo:3200
        - name: Loki
          type: loki
          url: http://loki:3100

# Tempo configuration
tempo:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

# Loki configuration
loki:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  config:
    auth_enabled: false

# Vault configuration
vault:
  enabled: true
  server:
    dev:
      enabled: ${eq .Values.global.environment "development"}
    ha:
      enabled: ${eq .Values.global.environment "production"}
    injector:
      enabled: true
    auth:
      kubernetes:
        enabled: true
  persistence:
    enabled: true

serviceAccounts:
  default:
    create: true
    name: "scholar-spark-service"
    annotations: {}
    permissions:
      - secrets
      - metrics
      - logs
