apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scholar-spark-service-binding
  labels: {{- include "shared-infra.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - kind: ServiceAccount
    name: scholar-spark-service
    namespace: {{ .Release.Namespace }}
