apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scholar-spark-service-role
  labels: {{ - include "shared-infra.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
