apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scholar-spark-service-role
  labels: {{- include "shared-infra.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    meta.helm.sh/release-name: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways", "httproutes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]