apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "shared-infra.labels" . | nindent 4 }}
data:
  config.yaml: |
    hubble:
      enabled: {{ .Values.cilium.hubble.enabled }}
      metrics:
        enabled: true
    ingressController:
      enabled: {{ .Values.cilium.ingressController.enabled }}
    kubeProxyReplacement: "strict"
    k8sServiceHost: "kubernetes.default.svc"
    k8sServicePort: "443"
    bpf:
      masquerade: true
    ipam:
      mode: "kubernetes"
    tunnel: "disabled"
    enableIPv4Masquerade: true
    enableIPv6Masquerade: false
    debug:
      enabled: true
  cni-config.json: |
    {
      "cniVersion": "0.3.1",
      "name": "cilium",
      "type": "cilium-cni",
      "enable-debug": true,
      "log-file": "/var/run/cilium/cilium-cni.log"
    }