apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium
  namespace: {{ .Release.Namespace }}
  labels: {{- include "shared-infra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilium
  template:
    metadata:
      labels:
        {{- include "shared-infra.labels" . | nindent 8 }}
        app: cilium
    spec:
      serviceAccountName: cilium
      hostNetwork: true
      containers:
        - name: cilium
          image: quay.io/cilium/cilium:v1.14.5
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "10.96.0.1"
            - name: KUBERNETES_SERVICE_PORT
              value: "443"
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CILIUM_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_MODULE
                - SYS_ADMIN
          volumeMounts:
            - name: bpf-maps
              mountPath: /sys/fs/bpf
              mountPropagation: Bidirectional
            - name: cilium-run
              mountPath: /var/run/cilium
            - name: cni-path
              mountPath: /opt/cni/bin
            - name: etc-cni-netd
              mountPath: /etc/cni/net.d
            - name: lib-modules
              mountPath: /lib/modules
            - name: xtables-lock
              mountPath: /run/xtables.lock
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      volumes:
        - name: bpf-maps
          hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
        - name: cilium-run
          hostPath:
            path: /var/run/cilium
            type: DirectoryOrCreate
        - name: cni-path
          hostPath:
            path: /opt/cni/bin
        - name: etc-cni-netd
          hostPath:
            path: /etc/cni/net.d
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock