apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shared-infra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        {{- include "shared-infra.labels" . | nindent 8 }}
        app: tempo
    spec:
      terminationGracePeriodSeconds: 60
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
      containers:
        - name: tempo
          image: grafana/tempo:2.3.0  # Specific version instead of latest
          args:
            - -config.file=/etc/tempo/tempo.yaml
          ports:
            - containerPort: 3200
            - containerPort: 4317
            - containerPort: 4318
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: data
              mountPath: /tmp/tempo
      volumes:
        - name: config
          configMap:
            name: tempo-config
        - name: data
          emptyDir: {} 