apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: {{ .Release.Namespace }}
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces

    compactor:
      compaction:
        block_retention: 24h

    ingester:
      max_block_duration: 5m

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: scholar-spark-dev 